name = "tau_green_agent"
description = "The assessment hosting agent for tau-bench."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]
[capabilities]
streaming = false

[[skills]]
id = "host_assess_finance_benchmark"
name = "Finance benchmark assessment hosting"
description = """
    Assess correct responses.
"""
tags = ["green agent", "assessment hosting", "tau-bench"]
examples = ["""    
Your task is to instantiate the finance benchmark to test the agent located at:
    <white_agent_url>
    http://localhost:9002/
    </white_agent_url>
You should use the following env configuration:
<env_config>
{
  "env": "retail",
  "user_strategy": "llm",
  "user_model": "google/gemini-2.5-pro",
  "user_provider": "google",
  "task_split": "test",
  "task_path" : "assets/data/public.csv",
  "task_ids": [
    1
  ]
}
</env_config>
"""]