name = "finben_green_agent"
description = "The assessment hosting agent for finance bench."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]
[capabilities]
streaming = false

[[skills]]
id = "host_assess_finance_benchmark"
name = "Finance benchmark assessment hosting"
description = """
    Assess correct responses and serves tools as skills.
"""
tags = ["green agent", "assessment hosting", "finance benchmark"]
examples = ["""    
Your task is to instantiate the finance benchmark to test the agent located at:
    <white_agent_url>
    http://localhost:9002/
    </white_agent_url>
You should use the following env configuration:
<env_config>
{
  "env": "retail",
  "user_strategy": "llm",
  "user_model": "google/gemini-2.5-pro",
  "user_provider": "google",
  "task_split": "test",
  "task_path" : "assets/data/public.csv",
  "task_ids": [
    1
  ]
}
</env_config>
"""]

# Expose tools as skills (https://a2a-protocol.org/latest/tutorials/python/3-agent-skills-and-card/#agent-skills)
# - Web search tool https://github.com/vals-ai/finance-agent/blob/main/tools.py#L114
[[skills]]
id = "google_search_tool"
name = "Google Search tool"
description = """
    Uses the SerpAPI to search the web.
"""
tags = ["green agent", "tools", "search web"]
examples = ["""    
  search_query: sql
  response: SQL is a query language used mostly for interacting with relational database management systems.
"""]